# min max normalizaion

In [ ]:
import numpy as np

# Example data
data = np.array([[1, 2], [2, 4], [3, 6], [4, 8]])

# Min-Max Normalization
data_min = data.min(axis=0)
data_max = data.max(axis=0)
normalized_data = (data - data_min) / (data_max - data_min)

print("Original Data:\n", data)
print("Min-Max Normalized Data:\n", normalized_data)

Original Data:
 [[1 2]
 [2 4]
 [3 6]
 [4 8]]
Min-Max Normalized Data:
 [[0.         0.        ]
 [0.33333333 0.33333333]
 [0.66666667 0.66666667]
 [1.         1.        ]]


In [3]:
from sklearn.preprocessing import MinMaxScaler

# Example data
data = [[1, 2], [2, 4], [3, 6], [4, 8]]

scaler = MinMaxScaler(feature_range=(0, 1))
normalized_data = scaler.fit_transform(data)

print("Min-Max Normalized Data:\n", normalized_data)


Min-Max Normalized Data:
 [[0.         0.        ]
 [0.33333333 0.33333333]
 [0.66666667 0.66666667]
 [1.         1.        ]]


# Z-score normalization

In [ ]:
import numpy as np

# Example data
data = np.array([[1, 2], [2, 4], [3, 6], [4, 8]])

# Z-Score Normalization
mean = data.mean(axis=0)
std = data.std(axis=0)
standardized_data = (data - mean) / std

print("Original Data:\n", data)
print("Z-Score Normalized Data:\n", standardized_data)

Original Data:
 [[1 2]
 [2 4]
 [3 6]
 [4 8]]
Z-Score Normalized Data:
 [[-1.34164079 -1.34164079]
 [-0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079]]


In [21]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

# Example DataFrame
data = {
    "Feature1": [1, 2, 3, 4],
    "Feature2": [2, 4, 6, 8]
}
df = pd.DataFrame(data)

# Initialize the StandardScaler
scaler = StandardScaler()

# Perform standardization
standardized_data = scaler.fit_transform(df)

# Convert back to a DataFrame
standardized_df = pd.DataFrame(standardized_data, columns=df.columns)

print("Original DataFrame:\n", df)
print("\nZ-Score Normalized DataFrame:\n", standardized_df)



Original DataFrame:
    Feature1  Feature2
0         1         2
1         2         4
2         3         6
3         4         8

Z-Score Normalized DataFrame:
    Feature1  Feature2
0 -1.341641 -1.341641
1 -0.447214 -0.447214
2  0.447214  0.447214
3  1.341641  1.341641


# L2 form 

In [ ]:
import numpy as np

# Example data
data = np.array([[1, 2], [3, 4], [5, 6]])

# L2 Normalization
l2_norm = np.linalg.norm(data, axis=1, keepdims=True)
normalized_data = data / l2_norm

print("Original Data:\n", data)
print("L2 Normalized Data:\n", normalized_data)

Original Data:
 [[1 2]
 [3 4]
 [5 6]]
L2 Normalized Data:
 [[0.4472136  0.89442719]
 [0.6        0.8       ]
 [0.6401844  0.76822128]]


In [13]:
from sklearn.preprocessing import Normalizer

# Example data
data = [[1, 2], [3, 4], [5, 6]]

normalizer = Normalizer(norm='l2')
normalized_data = normalizer.fit_transform(data)

print("L2 Normalized Data:\n", normalized_data)


L2 Normalized Data:
 [[0.4472136  0.89442719]
 [0.6        0.8       ]
 [0.6401844  0.76822128]]
